robot1:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  arm_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - base_to_arm_base
      - arm_1_to_arm_base
      - arm_2_to_arm_1

    constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      base_to_arm_base: {trajectory: 0.1, goal: 0.1}
      arm_1_to_arm_base: {trajectory: 0.1, goal: 0.1}
      arm_2_to_arm_1: {trajectory: 0.1, goal: 0.1}

    stop_trajectory_duration: 0.5
    state_publish_rate: 25
    action_monitor_rate: 10


  gripper_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - left_gripper_joint
      - right_gripper_joint

    constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      left_gripper_joint: {trajectory: 0.1, goal: 0.1}
      right_gripper_joint: {trajectory: 0.1, goal: 0.1}

    stop_trajectory_duration: 0.5
    state_publish_rate: 25
    action_monitor_rate: 10
    
    # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: base_to_arm_base
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: arm_1_to_arm_base
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: arm_2_to_arm_1
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_gripper_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_gripper_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}    
